export const DATABASE_CONNECTION_URI = 'DATABASE_CONNECTION_URI';
export const DATABASE_USER = 'DATABASE_USER';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const USER_TOKEN_SECRET = 'USER_TOKEN_SECRET';
export const TOKEN_EXPIRY_DURATION = 'TOKEN_EXPIRY_DURATION';
export const REDIS_HOST = 'REDIS_HOST';
export const REDIS_PORT = 'REDIS_PORT';
